#!/usr/bin/env bash
# =============================================================================
# Setup script for the SIEM AI Agent on the EC2 producer host.
#
# Fully self-contained — independent of the siem-emulator (main demo) setup.
# Installs Node.js, Python venv, builds the mcp-confluent server, and writes
# an env file (~/.ai-demo.env) that agent.py reads.
#
# Run once after ai-demo/copy-to-ec2.sh has copied the files to the EC2:
#   bash ~/ai-demo/setup-ai-demo.sh
#
# To reload the environment in a new shell:
#   source ~/.ai-demo.env
# =============================================================================

set -euo pipefail

log() { echo "[$(date +%H:%M:%S)] $*"; }
die() { echo "ERROR: $*" >&2; exit 1; }

# ── Defaults — override by exporting before running this script ───────────────
# Bootstrap/URL/credential defaults match the deployment settings in edge/ and
# hub/ CRDs (same convention as scripts/05-generate-client-configs.sh).
: "${BEDROCK_MODEL:=eu.anthropic.claude-haiku-4-5-20251001-v1:0}"
: "${MCP_CONFLUENT_REPO:=https://github.com/confluentinc/mcp-confluent.git}"
: "${NODE_VERSION:=22}"
: "${PYTHON_BIN:=python3.12}"
: "${HUB_BOOTSTRAP:=hub.kafka.demo:9092}"
: "${HUB_SR_URL:=https://schemaregistry.hub.kafka.demo:8081}"
: "${KAFKA_USER:=admin}"
: "${KAFKA_PASSWORD:=admin-secret}"
: "${SR_USER:=admin}"
: "${SR_PASSWORD:=admin-secret}"

# ── Paths ─────────────────────────────────────────────────────────────────────
AI_DEMO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MCP_DIR="${HOME}/mcp-confluent"
VENV_DIR="${AI_DEMO_DIR}/.venv"
CA_CERT="${AI_DEMO_DIR}/certs/cacerts.pem"
ENV_FILE="${HOME}/.ai-demo.env"

# ── 1. Node.js 22 ─────────────────────────────────────────────────────────────
log "Checking Node.js..."
NODE_OK=false
if command -v node &>/dev/null; then
  NODE_MAJOR=$(node --version | sed 's/v//' | cut -d. -f1)
  [[ "${NODE_MAJOR}" -ge "${NODE_VERSION}" ]] && NODE_OK=true
fi

if [[ "${NODE_OK}" == "false" ]]; then
  log "Installing Node.js ${NODE_VERSION} via nvm..."
  curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  export NVM_DIR="${HOME}/.nvm"
  # shellcheck disable=SC1091
  source "${NVM_DIR}/nvm.sh"
  nvm install "${NODE_VERSION}"
  nvm use "${NODE_VERSION}"
  nvm alias default "${NODE_VERSION}"
  log "Node.js $(node --version) installed."
else
  log "Node.js $(node --version) — OK"
fi

# Ensure node/npm are on PATH for this session
export NVM_DIR="${HOME}/.nvm"
[[ -s "${NVM_DIR}/nvm.sh" ]] && source "${NVM_DIR}/nvm.sh"

# ── 2. Clone and build mcp-confluent ─────────────────────────────────────────
if [[ -d "${MCP_DIR}/.git" ]]; then
  log "mcp-confluent already cloned — pulling latest..."
  (cd "${MCP_DIR}" && git pull --quiet)
else
  log "Cloning mcp-confluent..."
  git clone --quiet "${MCP_CONFLUENT_REPO}" "${MCP_DIR}"
fi

log "Checking pnpm..."
command -v pnpm &>/dev/null || { log "Installing pnpm..."; npm install -g pnpm --loglevel=error; }

log "Installing mcp-confluent dependencies..."
(cd "${MCP_DIR}" && pnpm install --frozen-lockfile)

log "Building mcp-confluent..."
(cd "${MCP_DIR}" && pnpm run build)

MCP_SERVER="${MCP_DIR}/dist/index.js"
[[ -f "${MCP_SERVER}" ]] || die "Build failed — ${MCP_SERVER} not found"
log "MCP server built: ${MCP_SERVER}"

# ── 3. Python virtual env + dependencies ─────────────────────────────────────
log "Checking ${PYTHON_BIN}..."
command -v "${PYTHON_BIN}" &>/dev/null || { log "Installing ${PYTHON_BIN}..."; sudo dnf install -y "${PYTHON_BIN}"; }

log "Setting up Python virtual env at ${VENV_DIR}..."
[[ -d "${VENV_DIR}" ]] || "${PYTHON_BIN}" -m venv "${VENV_DIR}"
PYTHON="${VENV_DIR}/bin/python"

"${PYTHON}" -m pip install --upgrade pip
"${PYTHON}" -m pip install -r "${AI_DEMO_DIR}/requirements.txt"
log "Python dependencies installed."

# ── 4. Write env file ─────────────────────────────────────────────────────────
log "Writing environment file to ${ENV_FILE}..."

[[ -f "${CA_CERT}" ]] || die "${CA_CERT} not found — run ai-demo/copy-to-ec2.sh first"

# AWS region — read from instance metadata if not already set
AWS_REGION="${AWS_REGION:-$(curl -sf --max-time 2 http://169.254.169.254/latest/dynamic/instance-identity/document | python3 -c "import sys,json; print(json.load(sys.stdin)['region'])" 2>/dev/null || echo "eu-west-2")}"

cat > "${ENV_FILE}" <<EOF
# Auto-generated by setup-ai-demo.sh — do not edit manually
export AWS_REGION="${AWS_REGION}"
export BEDROCK_MODEL="${BEDROCK_MODEL}"
export HUB_BOOTSTRAP="${HUB_BOOTSTRAP}"
export HUB_SR_URL="${HUB_SR_URL}"
export KAFKA_USER="${KAFKA_USER}"
export KAFKA_PASSWORD="${KAFKA_PASSWORD}"
export SR_USER="${SR_USER}"
export SR_PASSWORD="${SR_PASSWORD}"
export CA_CERT_PATH="${CA_CERT}"
export MCP_CONFIG_PATH="${AI_DEMO_DIR}/hub-mcp-config.yaml"
export MCP_SERVER_PATH="${MCP_SERVER}"

# Add nvm node to PATH
export NVM_DIR="\${HOME}/.nvm"
[ -s "\${NVM_DIR}/nvm.sh" ] && source "\${NVM_DIR}/nvm.sh"
EOF

log ""
log "=== Setup complete ==="
log ""
log "To start the AI agent:"
log "  source ~/.ai-demo.env"
log "  ${VENV_DIR}/bin/python ${AI_DEMO_DIR}/agent.py"
log ""
log "Or use the convenience wrapper:"
log "  bash ${AI_DEMO_DIR}/run-agent.sh"
