#!/usr/bin/env bash
# Creates all Kubernetes secrets required by the Hub cluster.
# Also creates the edge-ca-cert and edge-cluster-link-credential secrets
# needed by the ClusterLink resource on Hub.
#
# Usage:  KUBECTL_CONTEXT=<hub-ctx> ./scripts/02-create-secrets-hub.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="${SCRIPT_DIR}/.."
CERTS_DIR="${ROOT_DIR}/certs/hub"
CREDS_DIR="${ROOT_DIR}/hub/credentials"
EDGE_CERTS_DIR="${ROOT_DIR}/certs/edge"
NS="cp-hub"
CTX="${KUBECTL_CONTEXT:-}"

log() { echo "[$(date +%H:%M:%S)] $*"; }

KCL="kubectl"
[[ -n "${CTX}" ]] && KCL="kubectl --context=${CTX}"

[[ -f "${CERTS_DIR}/kafka-server.pem"     ]] || { echo "ERROR: Run certs/generate-certs.sh first"; exit 1; }
[[ -f "${CERTS_DIR}/kafka-server-key.pem" ]] || { echo "ERROR: Run certs/generate-certs.sh first"; exit 1; }
[[ -f "${CERTS_DIR}/cacerts.pem"          ]] || { echo "ERROR: Run certs/generate-certs.sh first"; exit 1; }
[[ -f "${CERTS_DIR}/rootCAkey.pem"        ]] || { echo "ERROR: Run certs/generate-certs.sh first"; exit 1; }

log "Creating secrets in namespace ${NS} (context: ${CTX:-current})..."

log "  tls-kafka"
$KCL create secret generic tls-kafka \
  --namespace="${NS}" \
  --from-file=fullchain.pem="${CERTS_DIR}/kafka-server.pem" \
  --from-file=cacerts.pem="${CERTS_DIR}/cacerts.pem" \
  --from-file=privkey.pem="${CERTS_DIR}/kafka-server-key.pem" \
  --dry-run=client -o yaml | $KCL apply -f -

log "  ca-pair-sslcerts"
$KCL create secret generic ca-pair-sslcerts \
  --namespace="${NS}" \
  --from-file=ca.crt="${CERTS_DIR}/cacerts.pem" \
  --from-file=ca.key="${CERTS_DIR}/rootCAkey.pem" \
  --dry-run=client -o yaml | $KCL apply -f -

log "  credential"
$KCL create secret generic credential \
  --namespace="${NS}" \
  --from-file=plain.txt="${CREDS_DIR}/plain.txt" \
  --from-file=plain-users.json="${CREDS_DIR}/plain-users.json" \
  --from-file=basic.txt="${CREDS_DIR}/basic.txt" \
  --from-file=plain-interbroker.txt="${CREDS_DIR}/plain-interbroker.txt" \
  --from-file=kafka-server-listener-internal-plain-metrics.txt="${CREDS_DIR}/kafka-server-listener-internal-plain-metrics.txt" \
  --dry-run=client -o yaml | $KCL apply -f -

# -------------------------------------------------------------------------
# ClusterLink secrets — Edge CA cert + Edge credentials for cluster-link user
# Both Edge and Hub share the same CA (generated by generate-certs.sh),
# so we can reuse cacerts.pem from either cluster's cert dir.
# -------------------------------------------------------------------------
log "  edge-ca-cert (for ClusterLink TLS verification)"
$KCL create secret generic edge-ca-cert \
  --namespace="${NS}" \
  --from-file=cacerts.pem="${EDGE_CERTS_DIR}/cacerts.pem" \
  --dry-run=client -o yaml | $KCL apply -f -

log "  edge-cluster-link-credential"
$KCL create secret generic edge-cluster-link-credential \
  --namespace="${NS}" \
  --from-literal=plain.txt="username=cluster-link
password=clusterlink-secret" \
  --dry-run=client -o yaml | $KCL apply -f -

# -------------------------------------------------------------------------
# Next-gen Control Center (2.x) — basic-auth secrets for the bundled
# Prometheus + Alertmanager. Server secrets hold the allowed user list;
# client secrets hold the username/password the components + C3 present.
# All use the key `basic.txt`.
# -------------------------------------------------------------------------
log "  prometheus-credentials (server)"
$KCL create secret generic prometheus-credentials \
  --namespace="${NS}" \
  --from-file=basic.txt="${CREDS_DIR}/prometheus-credentials-secret.txt" \
  --dry-run=client -o yaml | $KCL apply -f -

log "  alertmanager-credentials (server)"
$KCL create secret generic alertmanager-credentials \
  --namespace="${NS}" \
  --from-file=basic.txt="${CREDS_DIR}/alertmanager-credentials-secret.txt" \
  --dry-run=client -o yaml | $KCL apply -f -

log "  prometheus-client-creds (client)"
$KCL create secret generic prometheus-client-creds \
  --namespace="${NS}" \
  --from-file=basic.txt="${CREDS_DIR}/prometheus-client-credentials-secret.txt" \
  --dry-run=client -o yaml | $KCL apply -f -

log "  alertmanager-client-creds (client)"
$KCL create secret generic alertmanager-client-creds \
  --namespace="${NS}" \
  --from-file=basic.txt="${CREDS_DIR}/alertmanager-client-credentials-secret.txt" \
  --dry-run=client -o yaml | $KCL apply -f -

log ""
log "=== Hub secrets created ==="
$KCL get secrets -n "${NS}"
