{
 "title": "Confluent Platform overview",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kafka_server_kafkaserver_brokerstate, namespace)"
    }
   },
   {
    "name": "kafka_connect_cluster_id",
    "label": "Kafka Connect Cluster ID",
    "query": {
     "query": "label_values(kafka_connect_cluster_id)"
    }
   },
   {
    "name": "ksqldb_cluster_id",
    "label": "ksqlDB Cluster ID",
    "query": {
     "query": "label_values(ksql_ksql_engine_query_stats_liveness_indicator,ksql_cluster)"
    }
   },
   {
    "name": "schema_registry_pod",
    "label": "Schema Registry Pod",
    "query": {
     "query": "label_values(kafka_schema_registry_registered_count,pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Zookeeper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Zookeeper nodes online",
   "type": "stat",
   "description": "Quorum Size of Zookeeper ensemble",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(zookeeper_nodecount{job=\"zookeeper\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Number of ZNodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(zookeeper_nodecount{job=\"zookeeper\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Alive Connections",
   "type": "stat",
   "description": "Number of Alive Connections",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zookeeper_numaliveconnections{job=\"zookeeper\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Number of Watchers",
   "type": "stat",
   "description": "Number of Watchers",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zookeeper_watchcount{job=\"zookeeper\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "stat",
   "description": "Number of Alive Connections",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zookeeper_outstandingrequests{job=\"zookeeper\",namespace=\"$namespace\"}",
     "legendFormat": "{{pod}} ({{member_type}})"
    }
   ]
  },
  {
   "title": "Kafka Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "description": "Number of active controllers in the cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount{job=\"kafka\",namespace=\"$namespace\"} > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Brokers Online",
   "type": "stat",
   "description": "Number of Brokers Online",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount{job=\"kafka\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "stat",
   "description": "Partitions that are online",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{job=\"kafka\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |).",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions{job=\"kafka\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Under Min ISR Partitions",
   "type": "stat",
   "description": "Number of partitions under min insync replicas.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underminisr{job=\"kafka\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions Count",
   "type": "stat",
   "description": "Number of partitions that dont have an active leader and are hence not writable or readable.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{job=\"kafka\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Schema Registry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Schema Registry Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kafka_schema_registry_registered_count{job=\"schemaregistry\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Schemas registered",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_schema_registry_registered_count{job=\"schemaregistry\",namespace=\"$namespace\",pod=~\"$schema_registry_pod\"})"
    }
   ]
  },
  {
   "title": "Schemas deleted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_schema_registry_schemas_deleted{job=\"schemaregistry\",namespace=\"$namespace\",pod=~\"$schema_registry_pod\"})"
    }
   ]
  },
  {
   "title": "Kafka Connect ($kafka_connect_cluster_id) ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "repeat": "cluster",
   "targets": [
    {}
   ]
  },
  {
   "title": "Connect worker pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kafka_connect_connect_worker_metrics_connector_count{namespace=\"$namespace\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\"})"
    }
   ]
  },
  {
   "title": "Tasks Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_total_task_count{namespace=\"$namespace\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\"})"
    }
   ]
  },
  {
   "title": "Tasks Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_running_task_count{namespace=\"$namespace\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\"})"
    }
   ]
  },
  {
   "title": "Tasks Paused",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_paused_task_count{namespace=\"$namespace\",pod=~\"$pod\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_failed_task_count{namespace=\"$namespace\",pod=~\"$pod\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Time since last rebalance ",
   "type": "stat",
   "description": "Time since last rebalance",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "clockms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_rebalance_metrics_time_since_last_rebalance_ms{namespace=\"$namespace\",job=\"connect\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\"} >= 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ksqlDB Cluster ($ksqldb_cluster_id) ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "repeat": "clusterid",
   "targets": [
    {}
   ]
  },
  {
   "title": "ksqlDB pods",
   "type": "stat",
   "description": "Average number of active queries per server.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ksql_ksql_engine_query_stats_num_active_queries{job=\"ksqldb\", namespace=\"$namespace\", ksql_cluster=\"$ksqldb_cluster_id\"})"
    }
   ]
  },
  {
   "title": "Active Queries",
   "type": "stat",
   "description": "Average number of active queries per server.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ksql_ksql_engine_query_stats_num_active_queries{job=\"ksqldb\", namespace=\"$namespace\", ksql_cluster=\"$ksqldb_cluster_id\"})"
    }
   ]
  },
  {
   "title": "Running Queries",
   "type": "stat",
   "description": "Num of created queries",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ksql_ksql_engine_query_stats_running_queries{job=\"ksqldb\", namespace=\"$namespace\", ksql_cluster=\"$ksqldb_cluster_id\"})"
    }
   ]
  },
  {
   "title": "Rebalancing Queries",
   "type": "stat",
   "description": "Num of rebalancing queries",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ksql_ksql_engine_query_stats_rebalancing_queries{job=\"ksqldb\", namespace=\"$namespace\", ksql_cluster=\"$ksqldb_cluster_id\"})"
    }
   ]
  },
  {
   "title": "Queries in Error State",
   "type": "stat",
   "description": "Number of error query",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ksql_ksql_engine_query_stats_error_queries{job=\"ksqldb\", namespace=\"$namespace\", ksql_cluster=\"$ksqldb_cluster_id\"})"
    }
   ]
  },
  {
   "title": "Stopped Queries",
   "type": "stat",
   "description": "Num of not running queries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ksql_ksql_engine_query_stats_not_running_queries{job=\"ksqldb\", namespace=\"$namespace\", ksql_cluster=\"$ksqldb_cluster_id\"})"
    }
   ]
  }
 ]
}