{
 "title": "Kafka Topics",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kafka_log_log_size, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_server_kafkaserver_brokerstate{namespace=\"${namespace}\"}, pod)"
    }
   },
   {
    "name": "topic",
    "label": "Topic name",
    "query": {
     "query": "label_values(kafka_log_log_size{namespace=\"${namespace}\",pod=~\"$pod\"},topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total # of Topics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globaltopiccount{job=\"kafka\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Messages In",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum without(pod) (rate(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka\",topic=~\"$topic\",namespace=~\"$namespace\"}[5m])))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Log size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, sum(kafka_log_log_size{job=\"kafka\",namespace=\"$namespace\",topic=~\"$topic\"}) by (topic))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Total # of Partitions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globalpartitioncount{job=\"kafka\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(10, sum without(pod) (rate(kafka_server_brokertopicmetrics_bytesinpersec{job=\"kafka\",topic=~\"$topic\",namespace=~\"$namespace\"}[5m])))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(10, sum without(pod) (rate(kafka_server_brokertopicmetrics_bytesoutpersec{job=\"kafka\",topic=~\"$topic\",namespace=~\"$namespace\"}[5m])))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Produce Request per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(kafka_server_brokertopicmetrics_totalproducerequestspersec{job=\"kafka\", namespace=\"$namespace\", topic=~\"$topic\"}[5m])) by (topic))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Fetch Request per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(kafka_server_brokertopicmetrics_totalfetchrequestspersec{job=\"kafka\", namespace=\"$namespace\",topic=~\"$topic\"}[5m])) by (topic))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Topic offsets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Start Offset",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "kafka_log_log_logstartoffset{job=\"kafka\",namespace=~\"$namespace\",pod=~\"$pod\",topic=~\"$topic\"}"
    }
   ]
  },
  {
   "title": "End Offset",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "kafka_log_log_logendoffset{job=\"kafka\",namespace=~\"$namespace\",pod=~\"$pod\",topic=~\"$topic\"}"
    }
   ]
  },
  {
   "title": "Tiered Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true
  },
  {
   "title": "Tiered size",
   "type": "timeseries",
   "description": "Total tier size",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, sum(kafka_log_log_tiersize{job=\"kafka\",namespace=\"$namespace\",topic=~\"$topic\"}) by (topic))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Storage distribution",
   "type": "piechart",
   "description": "Total tier size",
   "gridPos": { "h": 10, "w": 7, "x": 9, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_log_log_tiersize{job=\"kafka\",namespace=\"$namespace\",topic=~\"$topic\"}) by (namespace)",
     "legendFormat": "tier size"
    },
    {
     "expr": "sum(kafka_log_log_size{job=\"kafka\",namespace=\"$namespace\",topic=~\"$topic\"}) by (namespace)",
     "legendFormat": "disk"
    }
   ]
  }
 ]
}